name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: 0 0 */7 * *  # run every 7 days
jobs:
  build:
    name: Build container and push to dockerhub
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: |
          docker build . -t rouhim/archlinux-binutils
          docker push rouhim/archlinux-binutils

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rouhim/archlinux-binutils